CREATE TABLE Freelancer (

  ID INT PRIMARY KEY NOT NULL,
  ADDRESSID INT FOREIGN KEY NOT NULL,
  EDUCATION VARCHAR NOT NULL,
  AVAILABILITY BIT NOT NULL,
  WORKING_AREA VARCHAR NOT NULL,
  RATE DECIMAL(10,2) NOT NULL --reevaluate datatype
)